F:
  shape: [ 4, 4 ]
  data: [ 1.0, 0.0, 1.0, 0.0,
          0.0, 1.0, 0.0, 1.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0 ]
P:
  shape: [ 4, 4 ]
  data: [ 1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1000.0, 0.0,
          0.0, 0.0, 0.0, 1000.0 ]
Q:
  shape: [ 4, 4 ]
  data: [ 1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0 ]

H:
  shape: [ 2, 4 ]
  data: [ 1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0 ]

U:
  shape: [ 4, 1 ]
  data: [ 0.0, 0.0, 0.0, 0.0 ]

R_lidar:
  shape: [ 2, 2 ]
  data: [ 0.0225, 0.0,
          0.0, 0.0225 ]

R_radar:
  shape: [ 3, 3 ]
  data: [ 0.09,    0.0,  0.0,
          0.0, 0.0009,  0.0,
          0.0,    0.0,  0.09 ]

#set the acceleration noise components
noise_ax: 9.0
noise_ay: 9.0

use_control: false
